version: "3.8"

services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"  
    networks:
      - my_network



  news-site:
    container_name: news-site
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/app/app:Z
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
    networks:
      - my_network
    command: sh -c "npm install && npx prisma migrate dev --name init && npx tsx ./prisma/seed.ts && npm run start"
    


  # nginx:
  #   image: nginx:1.21.0
  #   container_name: nginx_proxy
  #   restart: always
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - news-site

networks:
  my_network:
    external: true

volumes:
  postgres_data:
